Fix build failures due to undeclared wait()
error: ‘wait’ was not declared in this scope
         wait();
         ^~~~

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>